version: "3.8"
services:
  webapp:
    build:
      context: .
      dockerfile: ./docker/webapp.Dockerfile
    ports:
      - "8000:8000"
    environment:
      ENV: PROD
    volumes:
      - db_data:/data
      - secrets:/secrets
      - assets:/app/frontend/public
    links:
      - redis

  celery:
    build:
      context: .
      dockerfile: ./docker/webapp.Dockerfile
    environment:
      ENV: PROD
    volumes:
      - secrets:/secrets
      - db_data:/data
    links:
      - redis
    command: celery -A mysite worker -l INFO

  websocketserver:
    build:
      context: .
      dockerfile: ./docker/webapp.Dockerfile
    links:
      - redis
    ports:
      - "9000:9000"
    command: python3 -u websocket_server.py --redis-host redis

  nginx:
    image: nginx
    depends_on:
      - webapp
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - db_data:/data

  redis:
    image: redis

volumes:
  db_data:
  assets:
  secrets: