FROM python:3.10-slim

RUN apt-get update && apt-get install build-essential -y

RUN apt-get install git -y

RUN apt-get install curl alsa-utils libsdl2-dev -y

RUN git clone https://github.com/ggerganov/whisper.cpp.git && cd whisper.cpp && make && \
	bash ./models/download-ggml-model.sh base.en && make stream
	
