# Generated by Django 4.2.6 on 2023-11-03 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chat_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='prompt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat', to='chats.message'),
        ),
    ]
