# Generated by Django 4.2.6 on 2024-01-11 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_systemmessage_chat_system_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='system_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='chats.systemmessage'),
        ),
    ]
