# Generated by Django 4.2.6 on 2024-01-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_preset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
