# Generated by Django 4.2.6 on 2024-01-19 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='chats.configuration'),
        ),
    ]
