# Generated by Django 4.2.6 on 2024-03-07 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_chat_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
