# Generated by Django 4.2.6 on 2024-05-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_configuration_file_name_configuration_launch_params_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='template_spec',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
