# Generated by Django 4.2.6 on 2024-05-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_configuration_template_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/audio'),
        ),
    ]
