# Generated by Django 4.2.6 on 2024-06-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0013_message_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('audio', models.FileField(upload_to='uploads/audio')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
