# Generated by Django 4.2.6 on 2024-06-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0014_speechsample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='system_message',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
