# Generated by Django 4.2.6 on 2024-06-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0016_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachments_text',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=512)),
                ('file', models.FileField(upload_to='uploads/attachments')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chats.message')),
            ],
        ),
    ]
