# Generated by Django 4.2.14 on 2024-07-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0017_message_attachments_text_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='voice_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
