# Generated by Django 4.2.14 on 2024-08-21 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0018_configuration_voice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='presets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
